### ISSUE TITLE
Upkeep & optimizations

### ISSUE THREAD

**Issue by hazcod** [oec/goproxy#3]
Hi! I've noticed you forked goproxy too.
Did you do a lot of optimizations on your fork? I'm going over the code and optimizing where I can as wel.
So I'm wondering to re-base on your fork or not.

**Comment by hazcod** [comment]
https://github.com/hazcod/goproxy/commits/master

**Comment by oec** [comment]
Hey @hazcod,

the reason I forked goproxy was because of a mix of some optimization (cert-cache), bug fixes and missing features (websocket, cert-cache).  We use the fork in a project with a client.  It looks like you have forked your branch from a much later state of goproxy than my fork, so I would not recommend to re-base your fork on mine.

But I'm pretty much interested in improving goproxy, too, so I will watch your progress and might contribute, too. (once I can spent time on it)

Cheers from Berlin,
Özgür
